title: Lab nghiên cứu Dược liệu
description: Team nghiên cứu dược liệu Đại học Dược Hà Nội
url: "https://your-domain.com"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:name
