title: Lab nghiên cứu Dược liệu
description: website của Team nghiên cứu dược liệu, Đại học Dược Hà Nội
url: "https://hoangmanhhaa.github.io"
baseurl: "/Team-c-H-ngg"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Collections
collections:
  research:
    output: true
  publications:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
