title: Lab nghiên cứu Dược liệu
description: website của Team nghiên cứu dược liệu, Đại học Dược Hà Nội
url: "https://hoangmanhhaa.github.io"
baseurl: "/Team-c-H-ngg"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
# Collections
collections:
  research:
    output: true
  publications:
    output: true
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
