title: Lab nghiên cứu Dược liệu
description: website cuar Team nghiên cứu dược liệu, Đại học Dược Hà Nội
url: "https://hoangmanhhaa.github.io"
baseurl: "/Team-c-H-ngg"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:name
